Controllers/AdministrationController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using hello_blog_ui.Interfaces;
using hello_blog_ui.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace hello_blog_ui.Controllers
{
    public class AdministrationController : BaseController
    {
        public readonly IAdministrationApiManager _administrationApiManager;

        public AdministrationController(IAdministrationApiManager administrationApiManager)
        {
            _administrationApiManager = administrationApiManager;
        }

        public async Task<IActionResult> Index()
        {
            var cookieValue = GetCookie();
            var response = await _administrationApiManager.GetRolesAsync(cookieValue);
            var content = await response.Content.ReadAsStringAsync();
            var roles = JsonConvert.DeserializeObject<List<RoleModel>>(content);

            if (roles != null)
                return View(roles);
                
            return View();
        }
    }
}

Controllers/BlogPostController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using hello_blog_ui.Models;
using Microsoft.AspNetCore.Mvc;
using hello_blog_ui.Managers;
using hello_blog_ui.Interfaces;
using System.IO;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;

namespace hello_blog_ui.Controllers
{
    ///<summary>
    /// The only responsibility of BlogPostController class is to receive UI requests
    ///     - pass what is need to other layers
    ///     - respond to UI
    /// Version of the class obtained applying 
    ///     - SRP (create a new class that is responsible to build images)
    ///     - OCP (We've add the BulkPublish method (Open for extension))
    ///     - DIP (We've use Dependency Injection (DI) to inject what we need and create abstractions and get instance at Run Time)
    ///         - Regarding memory issue we should not instantiate classes and let .NET to do that.
    ///             - Just register the service in the Startup class -> RegisterServices method
    ///         - Controller pass the information to managers
    ///         - Controller does not know what is the implementation of managers
    ///</summary>
    public class BlogPostController : BaseController
    {
        private readonly IBlogPostApiManager _blogPostApiManager;
        private readonly IBlogPostManager _blogPostManager;
        private readonly IBlogViewsApiManager _blogViewsApiManager;
        private readonly IBlogPostViewsApiManager _blogPostViewsApiManager;

        public BlogPostController(IBlogPostApiManager blogPostApiManager,
                                  IBlogPostManager blogPostManager,
                                  IBlogViewsApiManager blogViewsApiManager,
                                  IBlogPostViewsApiManager blogPostViewsApiManager)
        {
            _blogPostApiManager = blogPostApiManager;
            _blogPostManager = blogPostManager;
            _blogViewsApiManager = blogViewsApiManager;
            _blogPostViewsApiManager = blogPostViewsApiManager;
        }

        ///<summary>
        /// Was refactored to pass the responsibility of building images to other layers
        ///</summary>
        public async Task<IActionResult> Index()
        {
            var stopWatch = new Stopwatch();
            stopWatch.Start();

            var blogPosts = Task.Run(() => _blogPostManager.GetBlogPosts());
            var viewsResponse = Task.Run(() => _blogViewsApiManager.GetAsync());
            await Task.WhenAll(blogPosts, viewsResponse);

            stopWatch.Stop();
            TimeSpan executionTime = TimeSpan.FromMilliseconds(stopWatch.ElapsedMilliseconds);
            var views = viewsResponse.Result.Content.ReadAsStringAsync().Result;
            var model = new BlogPostModel
            {
                BlogPosts = blogPosts?.GetAwaiter().GetResult(),
                ExecutionTime = executionTime.ToString(@"ss\:fff"),
                BlogNumberOfViews = JsonConvert.DeserializeObject<BlogViewsModel>(views)?.Views.ToString(),
                IsAuthenticated = CheckAuthentication()
            };

            if (!CheckAuthentication())
                Task.Factory.StartNew(() => { _blogViewsApiManager.UpdateAsync(); });

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        ///<summary>
        /// Was refactored to pass the responsibility of save blog post other layers
        ///</summary>
        [HttpPost]
        public async Task<IActionResult> Create(BlogPostApiModel blogPost)
        {
            if (ModelState.IsValid)
            {
                var cookieValue = GetCookie();
                await _blogPostApiManager.CreateAsync(blogPost, cookieValue);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        public async Task<IActionResult> View(int blogPostId)
        {
            var blogPost = _blogPostManager.GetBlogPostById(blogPostId);

            if (blogPost.Id < 1)
            {
                return View("Error", new ErrorModel { Error = "The blog post does not exist" });
            }

            // update number of views only if this a guest
            if(!CheckAuthentication())
                Task.Run(() => _blogPostViewsApiManager.UpdateAsync(blogPostId));

            return View(blogPost?.Result);
        }

        public async Task<IActionResult> Edit(int blogPostId, bool edit = false)
        {
            if (CheckAuthentication())
            {
                var model = new BlogPostApiModel();

                var blogPost = Task.Run(() => _blogPostManager.GetBlogPostById(blogPostId));
                var blogPostNumberOfViewes = Task.Run(() => _blogPostViewsApiManager.GetAsync(blogPostId));
                await Task.WhenAll(blogPost, blogPostNumberOfViewes);

                var blogPostViews = blogPostNumberOfViewes.Result.Content.ReadAsStringAsync().Result;
                var numberOfViews = JsonConvert.DeserializeObject<BlogPostViewsModel>(blogPostViews)?.Views.ToString();
                if (blogPost?.Result != null)
                {
                    blogPost.Result.Edit = edit;
                    blogPost.Result.NumberOfViews = !string.IsNullOrWhiteSpace(numberOfViews) ? numberOfViews : "0";
                }

                if (blogPost?.Result?.Id < 1)
                {
                    return View("Error", new ErrorModel { Error = "The blog post does not exist" });
                }

                return View(blogPost?.Result);
            }
            return View("Error", new ErrorModel { Error = "Operation not allowed! User is log authenticated." });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BlogPostApiModel blogPost)
        {
            if (CheckAuthentication())
            {
                var cookieValue = GetCookie();
                var updated = await _blogPostManager.Update(blogPost, cookieValue);

                if (!updated)
                {
                    return View("Error", new ErrorModel { Error = "The blog post does not exist" });
                }
                return RedirectToAction(nameof(Index));
            }
            return View("Error", new ErrorModel { Error = "Operation not allowed! User is log authenticated." });
        }

        public async Task<IActionResult> Delete(int blogPostId)
        {
            if (CheckAuthentication())
            {
                var cookieValue = GetCookie();
                var deleted = await _blogPostManager.DeleteBlogPostById(blogPostId, cookieValue);

                if (!deleted)
                {
                    return View("Error", new ErrorModel { Error = "The blog post does not exist" });
                }
                return RedirectToAction(nameof(Index));
            }
            return View("Error", new ErrorModel { Error = "Operation not allowed! User is log authenticated." });
        }

        ///<summary>
        /// Was added to show OCP (Open for extension)
        ///</summary>
        public async Task<IActionResult> BulkPublish([FromServices] IServiceProvider serviceProvider, BlogPostModel blogPostModel)
        {
            var formFile = blogPostModel.BulkBlogPosts;
            if (formFile?.Length > 0)
            {
                var fileName = formFile.FileName;
                var fileTypeString = Path.GetExtension(fileName).Substring(1);
                switch (fileTypeString)
                {
                    case "xml":
                        var serviceInstance = serviceProvider.GetService<ProcessXmlBlogData>();
                        await serviceInstance.PublishFromFile(formFile);
                        break;

                    case "json":
                        var serviceInstance1 = serviceProvider.GetService<ProcessJsonBlogData>();
                        await serviceInstance1.PublishFromFile(formFile);
                        break;
                    default:
                        break;
                }
            }

            return Redirect(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cognizant Softvision</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Shared/Layout.css"/>  
    <link rel="stylesheet" href="~/css/BlogPost/Index.css"/>  
    <link rel="stylesheet" href="~/css/BlogPost/Create.css"/>  
    <link rel="stylesheet" href="~/css/BlogPost/Edit.css"/>
    <link rel="stylesheet" href="~/css/Account/Login.css"/>  
    <link rel="stylesheet" href="~/css/Account/Register.css"/>  
</head>
<body>
    @using Microsoft.AspNetCore.Http
    @inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
    @{
        var isAuthenticated = HttpContextAccessor.HttpContext.Session.GetString("isAuthenticated");
        var role = HttpContextAccessor.HttpContext.Session.GetString("role");
    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container d-flex justify-content-between">
                @* Code commented because it runs in sync way *@
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cognizant Softvision Blog</a> *@
                <a class="navbar-brand text-color font-weight-bold underlined-text" asp-area="" asp-controller="BlogPost" asp-action="Index">Cognizant Softvision Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-grow-0">
                          
                    <ul class="navbar-nav">
                    @if(Convert.ToBoolean(isAuthenticated) && role != null && role.Equals("Admin")){
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="Index">Roles</a>
                        </li>
                    }      
                        
                    @if(!Convert.ToBoolean(isAuthenticated))
                    {
                            <li class="nav-item">
                                <a class="nav-link text-dark text-color font-weight-bold underlined-text" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark text-color font-weight-bold underlined-text" asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a>
                            </li>
                    }
                    else
                    {
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <div class="input-group">
                                    <button type="submit" class="btn btn-link">Logout</button>
                                </div>
                            </form>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cognizant Softvision
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>